name: Test suite
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteorRelease:
          - '--release 3.0.1'
          - '--release 3.4'
          # Latest version
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Setup meteor ${{ matrix.meteorRelease }}
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ matrix.meteorRelease }}

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-

      - name: Run Tests
        run: |
          cd test-proxy
          npm ci
          npm run test
